### ISSUE TITLE
64-bit Minecraft Java Lunar install broken

### ISSUE THREAD

**Issue by bagong** [Botspot/pi-apps#1027]
The install script hangs at "- Downloading lwjgl3arm64". I don't understand why

After manually getting past that point, there is another error when downloading libwebp-imageio... It should download the ...64 image (I assume), but the install-script addresses the 32-bit version.

After bypassing these problems Lunar launcher comes up, but Java fails to start. Weirdly the Desktop entry refers to jdk 1.8.0_251 while the installer installs "jdk-16".

I think this is quite horribly broken ;-)

**Comment by gl91306** [comment]
The java version is hardcoded so you dont have to ever change it, cause java 16 works for all versions

**Comment by gl91306** [comment]
if you want to play all versions, i reccomend using a 32 bit os

**Comment by Botspot** [comment]
> The install script hangs at "- Downloading lwjgl3arm64". I don't understand why

Weird! I was able to replicate this.
```
#this hangs forever
wget -O ~/lwjgl3arm64.tar.gz 'https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm64.tar.gz' 2&>1

#this downloads in less than a second
wget -O ~/lwjgl3arm64.tar.gz 'https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm64.tar.gz'
```

> I think this is quite horribly broken ;-)

I think `wget` is horribly broken.
In any case, thank you for letting us know there was a problem. That's what we're here for! :)

**Comment by theofficialgman** [comment]
> The java version is hardcoded so you dont have to ever change it, cause java 16 works for all versions
@gl91306 
no... no it does not for some cases. vanilla 1.16.5 will work... but with some mods it does not (in particular the hydrogen fabric mod breaks and causes minecraft not to launch if you use java 16 on 1.16.5)

some might work, yes, but you are asking for disaster to use java 16 for everything

ALL vanilla minecraft versions 1.12.2 and older will not launch for me if I use java 16 for example. testing on ubuntu bionic arm64 with openjdk java 16 from the ppa. using java 8 is fine for those versions (and thats what microsoft ships for them)
they all exit with this error:
```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by Chaosdave34** [comment]
Found a way to fix it: #1030

**Comment by gl91306** [comment]
like litteraly im going to say this ONCE and ONCE FOR ALL:

**Comment by theofficialgman** [comment]
you don't get what I going at.... I'm not talking about adding custom mods, lol
there are potentially BREAKING ISSUES with the BUIT IN mods

**Comment by gl91306** [comment]
care to eleborate?

**Comment by theofficialgman** [comment]
view this reply again... https://github.com/Botspot/pi-apps/issues/1027#issuecomment-939192264
I can't view their mod list (maybe you have a link to whatever repo they host them on) so I can't say which ones will break... but its quite likely that at least some of them will

> Lunar client is a PVP client. It only supports the versions 1.7, 1.8, 1.12, 1.16, 1.17, 1.18, and It doesnt support any mods other than the ones it aldready HAS. It only needs java 16 for all the versions included to WORK

nope... we already debunked that theory. minecraft 1.12 and older do not launch on java-16 (THIS ISN'T EVEN ON LUNAR, it just doesn't work in general)... again read this post. 
https://github.com/Botspot/pi-apps/issues/1027#issuecomment-939192264

**Comment by gl91306** [comment]
it works perfectly fine for 32 bit oses, and 64 bit support is still in beta

**Comment by gl91306** [comment]
> read the post.... I WASN'T EVEN USE LUNAR CLIENT
> 
> but I can say that you shouldn't expect it to work on every system

i never expected it to work on all systems

**Comment by theofficialgman** [comment]
my point still stands.... 
java 16 will produce compatibility issues, there are mods that will crash with java 16 on older minecraft versions, some of which may be in the lunar client or may come to the lunar client

in light of that, I suggest using java 8 on everything up to 1.16.5

**Comment by gl91306** [comment]
> my point still stands.... java 16 will produce compatibility issues, there are mods that will crash with java 16 on older minecraft versions, some of which may be in the lunar client or may come to the lunar client
> 
> in light of that, I suggest using java 8 on everything up to 1.16.5
> 
> these are the reasons that the official minecraft launcher still uses java 8 up to 1.16.5


This is only relevant to 64 bit systems

**Comment by gl91306** [comment]
And what mods exactly wont work?????

**Comment by gl91306** [comment]
click in the cube of dots to change it

**Comment by gl91306** [comment]
i didnt make it

**Comment by gl91306** [comment]
how bout this. you try launching a lunar version thats below 1.13 on ur 64 bit os. when it crashes, send the contents of ~/.lunarclient/logs/renderer.log then wel see if its a java version problem

**Comment by gl91306** [comment]
idgaf

**Comment by theofficialgman** [comment]
> how bout this. you try launching a lunar version thats below 1.13 on ur 64 bit os. when it crashes, send the contents of ~/.lunarclient/logs/renderer.log then wel see if its a java version problem

can't do that with how your installer as written
you don't have lwjgl2 for arm64

**Comment by gl91306** [comment]
and where exactly would i have obtained it from the first place?

**Comment by gl91306** [comment]
i got all my lwjgls from [here](https://github.com/mikehooper/Minecraft/)

**Comment by gl91306** [comment]
> > how bout this. you try launching a lunar version thats below 1.13 on ur 64 bit os. when it crashes, send the contents of ~/.lunarclient/logs/renderer.log then wel see if its a java version problem
> 
> can't do that with how your installer as written (needs to be rewritten/updated) you don't have lwjgl2 for arm64
> 
> does your appimage actually look in ~/lwjgl2arm64 for lwjgl2 when needed?

yes

**Comment by gl91306** [comment]
where are the .so files tho

**Comment by gl91306** [comment]
mmkhay ill try and get them sorted

**Comment by theofficialgman** [comment]
I have a branch on my repo for each lwjgl version
default to 3.2.2 but there is a lwjgl 2.9.4 branch

**Comment by gl91306** [comment]
lol ok :D

**Comment by gl91306** [comment]
oop i fix 1 sec

**Comment by gl91306** [comment]
fixed

**Comment by theofficialgman** [comment]
also in general I don't like this script...
you really shouldn't be messing with the files in /opt/jdk or setting the update alternatives to your installed version
it will break your script if the user changes their default java version

you really should be specifying in lunar what java version you want to launch and not rely on the default

**Comment by gl91306** [comment]
i made it so lunar yoinks the specific java 16 in /opt/jdk

**Comment by gl91306** [comment]
done

**Comment by theofficialgman** [comment]
I still don't like that you are writing to /ope/jdk... thats not a directory you should really be writing to
I think its better if you move everything in the script to inside ~/lunarassets

that includes the lwjgl3arm64 and lwjgl2arm64 folders and the jdk-16.0.1+9-jre64 files

**Comment by gl91306** [comment]
i really dont wanna, casue i aldready coded them into the launcher, and to change that id have to re-compile and change a lot of stuff, so i think its fine as it is.

**Comment by theofficialgman** [comment]
ctrl+f replace all... 
its really poor practice
and things will break inevitably when a user deletes those files from their home directory
since they look like orphaned install files

**Comment by theofficialgman** [comment]
your script also never actually downloads this file... `jdk-16.0.1+9-jre.tar.gz`

**Comment by theofficialgman** [comment]
oh uhh... well sandboxing with chromium is broken in the appimage (at least for me)
```
[17668:1010/224634.555694:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_lunarcxLWCaf/chrome-sandbox is owned by root and has mode 4755.

```

**Comment by theofficialgman** [comment]
ok, I extracted and fixed the chrome-sandbox permissions but now all I get is a grey window on launch...
```
(node:18162) DeprecationWarning: file property is deprecated and will be removed in v5.

(Use `lunarclient --trace-deprecation ...` to show where the warning was created)

22:51:51.294 › Starting IPC server.

22:51:51.303 › Started IPC server.

22:51:51.875 (autoUpdater) › Checking for update

(node:18162) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.

Error: Can't initialize nvrm channel

Error: Can't initialize nvrm channel

22:51:52.461 (autoUpdater) › Error: HttpError: 404 

"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"

Headers: {

  "server": "GitHub.com",

  "date": "Mon, 11 Oct 2021 02:51:52 GMT",

  "content-type": "text/plain; charset=utf-8",

  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",

  "permissions-policy": "interest-cohort=()",

  "cache-control": "no-cache",

  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",

  "x-frame-options": "deny",

  "x-content-type-options": "nosniff",

  "x-xss-protection": "0",

  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",

  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",

  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",

  "content-encoding": "gzip",

  "set-cookie": [

    "_gh_sess=tXvX5qbLoGI8uKOdnRdeF39bPqPoMHmhxXdEcL0NgmtoB3WmUrysYHnebO0MF%2BVPPzukMBPYEJoinVhItvpDvfajBw3PKJ%2B14F%2BtORwvbeNdo1eryYy%2BQicJ9BAm0AeBPuIM3l0MNxdQS5J32UkR811uX5hsWsElcrslRD3kHziYA5Fc0qHxhu5AOU7%2BMP3LMzNKHjQ%2FgaGJeBXUf6b3qmWy1j2CzT%2BnD5aXMdDgaaIXVYqDtpdW95YeMEuyLbuigX1ktadXsRcLhJfKYPiSdA%3D%3D--Mc%2BHQUzjd9x4MJuY--WlpdsbkUPD%2B9L7Qhice68g%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",

    "_octo=GH1.1.1573753298.1633920712; Path=/; Domain=github.com; Expires=Tue, 11 Oct 2022 02:51:52 GMT; Secure; SameSite=Lax",

    "logged_in=no; Path=/; Domain=github.com; Expires=Tue, 11 Oct 2022 02:51:52 GMT; HttpOnly; Secure; SameSite=Lax"

  ],

  "content-length": "40",

  "x-github-request-id": "C25C:6447:1C78650:28416E5:6163A6C8"

}

    at createHttpError (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)

    at ElectronHttpExecutor.handleResponse (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:143:9)

    at ClientRequest.<anonymous> (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:98:16)

    at ClientRequest.emit (events.js:376:20)

    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)

    at SimpleURLLoaderWrapper.emit (events.js:376:20)

(node:18162) UnhandledPromiseRejectionWarning: HttpError: 404 

"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"

Headers: {

  "server": "GitHub.com",

  "date": "Mon, 11 Oct 2021 02:51:52 GMT",

  "content-type": "text/plain; charset=utf-8",

  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",

  "permissions-policy": "interest-cohort=()",

  "cache-control": "no-cache",

  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",

  "x-frame-options": "deny",

  "x-content-type-options": "nosniff",

  "x-xss-protection": "0",

  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",

  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",

  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",

  "content-encoding": "gzip",

  "set-cookie": [

    "_gh_sess=tXvX5qbLoGI8uKOdnRdeF39bPqPoMHmhxXdEcL0NgmtoB3WmUrysYHnebO0MF%2BVPPzukMBPYEJoinVhItvpDvfajBw3PKJ%2B14F%2BtORwvbeNdo1eryYy%2BQicJ9BAm0AeBPuIM3l0MNxdQS5J32UkR811uX5hsWsElcrslRD3kHziYA5Fc0qHxhu5AOU7%2BMP3LMzNKHjQ%2FgaGJeBXUf6b3qmWy1j2CzT%2BnD5aXMdDgaaIXVYqDtpdW95YeMEuyLbuigX1ktadXsRcLhJfKYPiSdA%3D%3D--Mc%2BHQUzjd9x4MJuY--WlpdsbkUPD%2B9L7Qhice68g%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",

    "_octo=GH1.1.1573753298.1633920712; Path=/; Domain=github.com; Expires=Tue, 11 Oct 2022 02:51:52 GMT; Secure; SameSite=Lax",

    "logged_in=no; Path=/; Domain=github.com; Expires=Tue, 11 Oct 2022 02:51:52 GMT; HttpOnly; Secure; SameSite=Lax"

  ],

  "content-length": "40",

  "x-github-request-id": "C25C:6447:1C78650:28416E5:6163A6C8"

}

    at createHttpError (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)

    at ElectronHttpExecutor.handleResponse (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:143:9)

    at ClientRequest.<anonymous> (/home/garrett/Downloads/squashfs-root/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:98:16)

    at ClientRequest.emit (events.js:376:20)

    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)

    at SimpleURLLoaderWrapper.emit (events.js:376:20)

(node:18162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:18162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Chaosdave34** [comment]
I've tested. All lunar versions from 1.7 to 1.18 work with java 16. There are just some small error. The install java folder hasn't the right name, that's why lunar can't "spawn java". When Name changed, all 1.16+ versions work. But not below. That's not because of java 16, there is now reason why higher version should work. It's because even when 1.8 is starting it's looking for libraries in lwjgl3arm64, not in lwjgl2. When you change both folders even 1.7-1.12 starts.

**Comment by gl91306** [comment]
idk man i just wanted to play lunar on the pi, and others wanted that too so i publicly released it, i really don't care about any file organizations or anything.

**Comment by gl91306** [comment]
:P

**Comment by Botspot** [comment]
> > And, by avoiding a name-change, the total number of users would not be reset to zero.
> 
> Wow I never thought Minecraft Java is the most popular app in pi-apps lol.

It's probably because ETA Prime centered his Pi-Apps video around Minecraft Java.

**Comment by theofficialgman** [comment]
closing because I "think" lunar works right now

**Comment by gl91306** [comment]
i think it work as well
