### ISSUE TITLE
phantom yad clicks

### ISSUE THREAD

**Issue by thepotatolover** [Botspot/pi-apps#2575]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Clicking any app to install it maxes out cpu and causes the os to lock up

### Description

Newest version of pi apps on rpi 4 8gb newest rpi os 64bit

When i click any app to install it, it then causes the cpu to go to 100% and eventually the os locks up fully for no reason

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/04/2024
Latest Pi-Apps version: 04/05/2024
Kernel: aarch64 6.6.20+rpt-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.4
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
YAD_XID IS 0X400003 (gets spammed)
Terminated (randomly shows)
sh: 1: echo: echo: I/O error (also randomly shows)
```

**Comment by Botspot** [comment]
Pi-Apps tries to run quickly, so when you are viewing the main top level of blue categories, the subcategories are being generated in the background. This involves reading a lot of files, so with a really slow SD card, you may encounter a brief freeze.

What kind of drive are you using to boot the Pi from? Have you benchmarked it with the `agnostics` tool? If not, please install `agnostics` with apt, then go to the start menu -> Accessories -> Raspberry Pi Diagnostics and follow the instructions.

**Comment by thepotatolover** [comment]
> Pi-Apps tries to run quickly, so when you are viewing the main top level of blue categories, the subcategories are being generated in the background. This involves reading a lot of files, so with a really slow SD card, you may encounter a brief freeze.
> 
> What kind of drive are you using to boot the Pi from? Have you benchmarked it with the `agnostics` tool? If not, please install `agnostics` with apt, then go to the start menu -> Accessories -> Raspberry Pi Diagnostics and follow the instructions.

im booting from a sd card and the diag gives it a pass

**Comment by thepotatolover** [comment]
> > im booting from a sd card and the diag gives it a pass
> 
> OK try this command and see if it causes the 100% cpu issue:
> 
> ```
> ~/pi-apps/preload yad ''
> ```
> 
> Please give it a few seconds. On my Pi4 it would usually only use some cpu in the first couple seconds.

alright would you like a video of the issue that is happening?

**Comment by thepotatolover** [comment]
I ran the command and it says `Preload-daemon skipped; nothing was changed`

**Comment by Botspot** [comment]
> I ran the command and it says `Preload-daemon skipped; nothing was changed`

ok, so then if you open pi-apps again, does it still have the 100% cpu issue?

**Comment by thepotatolover** [comment]
> > I ran the command and it says `Preload-daemon skipped; nothing was changed`
> 
> ok, so then if you open pi-apps again, does it still have the 100% cpu issue?

yes

**Comment by thepotatolover** [comment]
![image](https://github.com/Botspot/pi-apps/assets/142833759/7a14a6da-78df-4519-8165-e6d778e8cbf9)

**Comment by thepotatolover** [comment]
After the window opened at the end the entire rpi was locked up for about 4 minutes and it became responsive again and spammed the window open

https://github.com/Botspot/pi-apps/assets/142833759/e4cd8f7c-759a-412d-8d4d-5988f52bbf6f

![image](https://github.com/Botspot/pi-apps/assets/142833759/1a7f48ec-504f-4b5e-90d9-486dc4ec9e01)

**Comment by thepotatolover** [comment]
Fixed

dev connected tryed reproducing didnt work while dev was connected worked after a reboot and dev was disconnected after changing theme to another and changing it back the issue now doesnt seem to happen

**Comment by Botspot** [comment]
so basically, I could never reproduce it while connected to @thepotatolover with RustDesk, and after disconnecting, @thepotatolover could still not reproduce it until rebooting.
RustDesk connection seemed to fix it until a reboot.

@thepotatolover then switched to the xlunch theme, which worked fine, then switched back to yad-default where this issue no longer occurs.

@thepotatolover will re-open this issue if the issue returns. My theory is it's something graphics-related somehow causing `run_user_selection` to be run over and over, but this is unconfirmed.

**Comment by theofficialgman** [comment]
Yeah that is very strange. As indicated by the terminal logs yad is registering repeated clicks (calling `run_user_selection`) even when the user is (seemingly) only hovering.

That could be some strange filsystem corruption but I think it would need to be very specific. Maybe they are leaving out critical information like the presence of a rogue virtual mouse or touchscreen causing these phantom clicks.

Regardless its not a pi-apps issue itself.

**Comment by thepotatolover** [comment]
Tryed on 2 installs 1 on a usb ssd and an sd card and they both gave the same issue only had 1 keyboard and mouse that also works fine nothing else was plugged into usb except the mouse and keyboard and the usb ssd when i was booting from the ssd otherwise it would of just been the keyboard and mouse

**Comment by thepotatolover** [comment]
also they was both clean installs from the raspberry pi imager

**Comment by theofficialgman** [comment]
Can not reproduce on a fresh image
```
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/11/2024
Latest Pi-Apps version: 04/10/2024
Kernel: aarch64 6.6.20+rpt-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

As I said before, this is not a pi-apps issue. This appears to be a hardware issue. Your video can only be simulated by spamming the mouse left click on the GUI at very high (looks like 20 times per second in your video). Try using different peripherals (keyboard and mouse).

**Comment by thepotatolover** [comment]
i did same issue

**Comment by theofficialgman** [comment]
I don't really have any answer for you than swap out hardware one by one.
eg:
mouse
keyboard
storage
SOC (so if you have another pi, try it)
power supply

it is simply impossible to trigger multiple `run_user_selection` without selecting or double clicking on an entry in the yad list. So whatever hardware failure you have is causing many many additional mouse click actions.

**Comment by Botspot** [comment]
@thepotatolover were there ever any more updates to this? This is a very strange issue and you have been the only one to ever report it.

**Comment by theofficialgman** [comment]
Closing as unactionable.
