### ISSUE TITLE
"Remarkable" app's dependences missing (Can't install)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#401]
I've just installed it on my RPi OS 64-bit.
I'll do the install-32 next.

Here's install-64, pull #402

**Comment by fabianmendes** [comment]
`TODO:` add all dependencies to the **uninstall** file script, and create *install-32*; then, delete the `install` script file

**Comment by Botspot** [comment]
> `TODO:` add all dependencies to the **uninstall** file script, and create _install-32_; then, delete the `install` script file

Yeah... Moving files around like that can be tricky with pull requests.  And pull requests are harder download and test.

In this case, I'd say uploading your app as a .zip file would be better. Though both approaches have their downsides.

**Comment by fabianmendes** [comment]
> > `TODO:` add all dependencies to the **uninstall** file script, and create _install-32_; then, delete the `install` script file
> 
> Yeah... Moving files around like that can be tricky with pull requests. And pull requests are harder to download and test.
> 
> In this case, I'd say uploading your app as a .zip file would be better. Though both approaches have their downsides.

Ok, cool! Then, let me create the install-32 file now. I'll share here the ".zip"

**Comment by fabianmendes** [comment]
Ok, for install-32 it's ok (it doesn't need any dependence).

**Comment by fabianmendes** [comment]
See #402

**Comment by fabianmendes** [comment]
[Remarkable.zip](https://github.com/Botspot/pi-apps/files/6065332/Remarkable.zip)
Done?

**Comment by Botspot** [comment]
```
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
    #COMMANDS TO UNINSTALL 64BIT
    sudo apt purge gir1.2-webkit -y || error "Failed to purge gir1.2-webkit pacakge!"
    sudo apt purge gir1.2-javascriptcoregtk -y || error "Failed to purge gir1.2-javascriptcoregtk pacakge!"
    sudo apt purge libwebkitgtk -y || error "Failed to purge libwebkitgtk pacakge!"
    sudo apt purge libjavascriptcoregtk -y || error "Failed to purge libjavascriptcoregtk pacakge!"
    sudo apt purge libicu57 -y || error "Failed to purge libicus57 pacakge!"
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
    #COMMANDS TO UNINSTALL 32BIT
    sudo apt purge remarkable -y || error "Failed to purge remarkable package!"
sudo apt autoremove -y

else
    error "Failed to detect OS CPU architecture! Something is very wrong."
fi
```
This is better, but it's still not good. I can imagine some 64-bit OS users would have pre-installed `libwebkitgtk` beforehand.

You know what: it's a long shot, but `pkg-install` may just work. At least, if APT successfully installed it, then you can use `purge-installed` to uninstall packages at the end.  
Give it a try and see what happens. :)

**Comment by fabianmendes** [comment]
Sorry I've forgotten to ask about this:
"You know what: it's a long shot, but pkg-install may just work. At least,
if APT successfully installed it, then you can use purge-installed to
uninstall packages at the end."

I didn't get it bro, excuse me.

Otherwise, and out of context: I think I've done Unrar app, when you get
time please take a look into it :)
 ~V. Fabian T· Mendes C.

**Comment by fabianmendes** [comment]
> This is better, but it's still not good. I can imagine some 64-bit OS users would have pre-installed `libwebkitgtk` beforehand.
Then, How can we do here in order to uninstall?


> You know what: it's a long shot, but `pkg-install` may just work. At least, if APT successfully installed it, then you can use `purge-installed` to uninstall packages at the end.
> Give it a try and see what happens. :)

How should I write into my script/terminal/code?

**Comment by Botspot** [comment]
> How should I write into my script/terminal/code?

To test my theory, I went ahead and tried it for another app. It works!
```
wget https://debian.opennms.org/dists/opennms-25/main/binary-all/oracle-java8-installer_8u131-1~webupd8~2_all.deb || error "Failed to download oracle-java8-installer_8u131-1~webupd8~2_all.deb"

#sudo apt install -yf ~/oracle-java8-installer_8u131-1~webupd8~2_all.deb
"${DIRECTORY}/pkg-install" ~/"oracle-java8-installer_8u131-1~webupd8~2_all.deb" "$(dirname "$0")" || exit 1
```

**Comment by fabianmendes** [comment]
You say (do you thing think) that that way will install the exact
dependencies? I had to go to pkgs web site and copy its ftp url address as
you may seen before on the scripts.

The installations done successfully but I'm aware of uninstalling process.

**Comment by Botspot** [comment]
There, this ought to work:  
[Remarkable.zip](https://github.com/Botspot/pi-apps/files/6124908/Remarkable.zip)  
I just replaced the times you used apt, for `pkg-install`, and in the uninstall script, I switched to `purge-installed`.

**Comment by Botspot** [comment]
> There, this ought to work:
> [Remarkable.zip](https://github.com/Botspot/pi-apps/files/6124908/Remarkable.zip)

Yep, works great on 32-bit and 64-bit. And if the dependency packages are installed prior to installing Remarkable, then the uninstall script leaves them intact.

Added with commit 1522ac42ca1b9a38c1786f60751f7a3bca1dfcf2.

**Comment by fabianmendes** [comment]
🙏😁🙌🙌

**Comment by fabianmendes** [comment]
> "${DIRECTORY}/pkg-install" ~/"oracle-java8-installer_8u131-1~webupd8~2_all.deb" "$(dirname "$0")" || exit 1

I just did the same for #255 see -> 
[unrar.zip](https://github.com/Botspot/pi-apps/files/6134091/unrar.zip)
